topic:
  user-events: user-events

spring:
  kafka:
    bootstrap-servers: localhost:9092


  datasource:
    url: jdbc:postgresql://localhost:5432/springusers_db
    username: your_username
    password: your_username
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


